services:
  # --- 1. Database Service ---
  postgres-db:
    image: postgres:15-alpine
    container_name: jobfindhub-db
    environment:
      POSTGRES_DB: jobdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Admin@123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # --- 2. Backend API Service ---
  backend-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: jobfindhub-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/jobdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Admin@123
    depends_on:
      - postgres-db

  # --- 3. Frontend Web Service ---
  frontend-web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: jobfindhub-frontend
    ports:
      - "80:80"
    depends_on:
      - backend-api

  # --- 4. Prometheus Metric Collector ---
  prometheus:
    image: prom/prometheus:latest
    container_name: jobfindhub-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - backend-api

  # --- 5. Grafana Observability Dashboard Control Tower ---
  grafana:
    image: grafana/grafana:latest
    container_name: jobfindhub-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin # Default entry password layout
    depends_on:
      - prometheus

volumes:
  pgdata:

